### PR TITLE
Add ignore for Mac/tooling/IDE related folders

### LINKED ISSUE #8: Ignore some root folders
Add the following to .gitignore

tools/
build/
.nuget/
.dotnet/
.idea/
.[Dd][Ss]_[Ss]tore

### PR DESCRIPTION
**Pull request by erik-lundgren**
Fixes #8

### CODE REVIEW

**Comment by Aaronontheweb** [comment]
@erik-lundgren thanks for your contribution!

**Comment by ayoung** [comment]
@Aaronontheweb these need to be added to the dotnet template content as well.

**Comment by Aaronontheweb** [comment]
@ayoung good idea. Thought about adding .gitignore to it... We should just go ahead and do it IMHO

**Comment by ayoung** [comment]
i don't know if .gitignore files are included in the template content but i guess we'll find out.

**Pull request merged**
